spring.application.name=app

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/skills_talent
spring.datasource.username=postgres
spring.datasource.password=1234

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=TBqbSBOsvwNwmyu3fs3xKC/V2rD10BThKWc259rqeRVy1/n6V3TcqnWHoT7yk1JyqzCy2RVoInRF5xP40xOadQ==
jwt.expiration=86400000

# Mail (desactive en dev — remplacer par un vrai serveur en prod)
spring.mail.host=localhost
spring.mail.port=1025
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration

# Server
server.port=8080

# Claude AI (https://console.anthropic.com/settings/keys)
claude.api.key=